name: Build/Test
on:
  push:
    branches:
      - main
    paths:
      - 'Twingrind/**'
      - 'pytwingrind/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  Build:
    name: Build/Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3    
      - name: Build Twingrind
        uses: Zeugwerk/zkbuild-action@1.0.0
        with:
          username: ${{ secrets.ACTIONS_ZGWK_USERNAME }}
          password: ${{ secrets.ACTIONS_ZGWK_PASSWORD }}
      - name: Build pytwingrind
        run: |
          cd pytwingrind
          python setup.py bdist_wheel
          
